AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - "*.gemspec"
    - spec/**/*
    - vendor/**/*

Metrics/AbcSize:
  Severity: error

Metrics/ClassLength:
  Max: 250
  Severity: error

Metrics/CyclomaticComplexity:
  Severity: error

Metrics/MethodLength:
  Max: 10
  Severity: error

Metrics/ModuleLength:
  Max: 150
  Severity: error

Metrics/ParameterLists:
  Max: 4
  Severity: warning

Layout/LineLength:
  Max: 100
  Severity: error

# We thinks that's fine for specs
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Keep for now, easier with superclass definitions
Style/ClassAndModuleChildren:
  Enabled: false

# The ones we use must exist for the entire class hierarchy.
Style/ClassVars:
  Enabled: false

# Well, well, well
Style/Documentation:
  Enabled: false

# Keep single line bodys for if and unless
Style/IfUnlessModifier:
  Enabled: false

# We think that's the developers choice
Style/GuardClause:
  Enabled: false

# Backward compatibility
Style/OptionalBooleanParameter:
  Enabled: false

# Backwards compatibility
Style/SafeNavigation:
  Enabled: false

# Backwards compatibility
Style/SlicingWithRange:
  Enabled: false
